# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Book Club
tagline:          'A site for our bookclub!'
description:      'A site for our bookclub'
domain:           altuser6a.github.io  
url:              https://altuser6a.github.io/
baseurl:          /book_club

author:
  name:           'altuser6a'
  url:            todo

paginate:         2

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/altuser6a/book_club

plugins:
  - jekyll-paginate
